### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

In [2]:
### code here
import numpy as np
a=np.array([3,2,np.nan,1,10,12,10,9,5,np.nan,1,np.nan])
print("Original array:\n",a.reshape(3,4))
a=np.isnan(a)
a.shape
print("\nFind the missing data of the said array:\n",a.reshape(3,4))

Original array:
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [3]:
### code here 
a=np.arange(10)
b=np.arange(10)
np.array_equal(a,b)

True

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [4]:
## code here
a=np.arange(16)
b=a.reshape(4,4)
print("Original array:\n",b)
b[[0,3], :] = b[[3,0], :]
b[[1,2], :] = b[[2,1], :]
print("New array after swapping first and last rows of the said array:\n",b)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New array after swapping first and last rows of the said array:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [5]:
#### code here
a=np.array([1,2,3,4])
print("List in to array:\n",a)
b=np.array((91,2,3,4))
print("Tuple in to array:\n",b)

List in to array:
 [1 2 3 4]
Tuple in to array:
 [91  2  3  4]


###### 5. Write a NumPy program to find common values between two arrays.

In [6]:
### code here
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = np.array([1, 3, 4])
print("common values between two arrays:\n",np.intersect1d(ar1, ar2))

common values between two arrays:
 [1 3 4]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [7]:
### code here
a1=np.array([[1,2],[3,4],[5,6]])
print("Original array:\n",a1)
print("Reshape 2x3:\n",a1.reshape((2,3)))

Original array:
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [8]:
### code here
a2 = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:\n",a2)
unique, frequency = np.unique(a2, return_counts = True)
print("Frequency of unique values of the said array:")
print(np.array([unique,frequency]))

Original array:
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [9]:
### code here
x = np.array([[0,0,0],[1,2,3],[4,5,6]])
print("Original arrays:")
print("Array-1:\n",x)
y = np.array([10,11,12])
print("Array-2:\n",y)
result = x + y
print("\nNew Array:\n",result)

Original arrays:
Array-1:
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2:
 [10 11 12]

New Array:
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [10]:
### code here
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [11]:
## code here
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Third and fourth elements of the first and second rows")
print(arra_data[:2,2:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [12]:
### code here
today = np.datetime64('today', 'D')
print("Today: ", today)
yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D') 
print("Yesterday: ", yesterday)
tomorrow = np.datetime64('today', 'D')+ np.timedelta64(1, 'D') 
print("Tomorrow: ", tomorrow)

Today:  2023-02-07
Yesterday:  2023-02-06
Tomorrow:  2023-02-08


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [13]:
## code here
yearMonth = '2017-05'
date = np.busday_offset(yearMonth, 0,roll='forward',weekmask='Mon')
print("First Monday in May 2017:\n",date)

First Monday in May 2017:
 2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
